CREATE TABLE IF NOT EXISTS DbInfo (
    InfoKey NVARCHAR(30) PRIMARY KEY NOT NULL,
    InfoValue NVARCHAR(100) NULL);

CREATE TABLE IF NOT EXISTS Pages (
    Name NVARCHAR(30) PRIMARY KEY NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    NavIndex INT NOT NULL DEFAULT 0
);
